# Generated by Django 5.2 on 2025-04-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('autor', 'Autor'), ('avaliador', 'Avaliador'), ('admin', 'Administrador')], default='autor', max_length=20),
        ),
    ]
