# Generated by Django 5.2 on 2025-04-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0002_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='parecer_final',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
