# Generated by Django 5.2 on 2025-06-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0003_trabalho_parecer_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='trabalho',
            name='parecer_final',
        ),
        migrations.AddField(
            model_name='trabalho',
            name='email_contato',
            field=models.EmailField(default='nao_informado@exemplo.com', max_length=254),
            preserve_default=False,
        ),
    ]
