# Generated by Django 5.2 on 2025-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0004_remove_trabalho_autor_remove_trabalho_parecer_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
