# Generated by Django 5.2 on 2025-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0005_alter_trabalho_email_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='arquivo_pdf',
        ),
        migrations.RemoveField(
            model_name='trabalho',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='trabalho',
            name='email_contato',
        ),
        migrations.RemoveField(
            model_name='trabalho',
            name='palavras_chave',
        ),
        migrations.RemoveField(
            model_name='trabalho',
            name='resumo',
        ),
        migrations.RemoveField(
            model_name='trabalho',
            name='status',
        ),
        migrations.AddField(
            model_name='trabalho',
            name='aceite_termo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='agencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='arquivo_trabalho',
            field=models.FileField(blank=True, null=True, upload_to='trabalhos/'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='categoria',
            field=models.CharField(blank=True, choices=[('profissional', 'Profissional'), ('universitario', 'Universitário')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='comprovante_bancario',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='conta_corrente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='link_trabalho',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='microtema',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='registro_profissional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='veiculo_universidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
