# Generated by Django 5.2 on 2025-06-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0006_remove_trabalho_arquivo_pdf_remove_trabalho_autores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='categoria',
            field=models.CharField(blank=True, choices=[('jornalismo impresso', 'Jornalismo impresso'), ('webjornalismo', 'Webjornalismo'), ('fotojornalismo', 'Fotojornalismo'), ('radiojornalismo', 'Radiojornalismo'), ('telejornalismo', 'Telejornalismo'), ('jornalismo universitário', 'Jornalismo universitário')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='microtema',
            field=models.CharField(blank=True, choices=[('meio ambiente e desenvolvimento sustentável em sala de aula', 'Meio ambiente e desenvolvimento sustentável em sala de aula'), ('união de todos para o enfrentamento das mudanças climáticas', 'União de todos para o enfrentamento das mudanças climáticas'), ('mitigação no campo e as boas práticas já implementadas', 'Mitigação no campo e as boas práticas já implementadas'), ('uso consciente dos recursos hídricos no enfrentamento da estiagem', 'Uso consciente dos recursos hídricos no enfrentamento da estiagem'), ('energias limpas e renováveis para o desenvolvimento sustentável', 'Energias limpas e renováveis para o desenvolvimento sustentável'), ('ações de resiliência para um RS mais forte', 'Ações de resiliência para um RS mais forte'), ('soluções baseadas na natureza para promover a qualidade de vida da população', 'Soluções baseadas na natureza para promover a qualidade de vida da população'), ('recursos naturais do RS como potencial para o desenvolvimento econômico sustentável', 'Recursos naturais do RS como potencial para o desenvolvimento econômico sustentável'), ('nova vida: como estão os animais resgatados da enchente', 'Nova vida: como estão os animais resgatados da enchente')], max_length=83, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='nome_completo',
            field=models.CharField(default='Sem nome', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='registro_profissional',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='veiculo_universidade',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('avaliador', 'Avaliador')], default='avaliador', max_length=20),
        ),
    ]
