# Generated by Django 5.2 on 2025-06-11 03:02

import trabalhos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0007_alter_trabalho_categoria_alter_trabalho_microtema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='arquivo_trabalho',
            field=models.FileField(blank=True, null=True, storage=trabalhos.models.PublicMediaStorage(), upload_to='trabalhos/'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='comprovante_bancario',
            field=models.FileField(blank=True, null=True, storage=trabalhos.models.PublicMediaStorage(), upload_to='comprovantes/'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='registro_profissional',
            field=models.FileField(blank=True, null=True, storage=trabalhos.models.PublicMediaStorage(), upload_to='comprovantes/'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='veiculo_universidade',
            field=models.FileField(blank=True, null=True, storage=trabalhos.models.PublicMediaStorage(), upload_to='comprovantes/'),
        ),
    ]
