# Generated by Django 5.2 on 2025-06-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0008_alter_trabalho_arquivo_trabalho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
