# Generated by Django 5.2 on 2025-09-02 03:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0010_trabalho_status_alter_trabalho_registro_profissional_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='avaliador',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='recomendacao',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='trabalho',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='c_a_sensibilizacao_reflexao',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='c_b_relacao_tema_microtemas',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='c_c_info_tecnicas',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='c_d_originalidade',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='c_e_apresentacao',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='decisao',
            field=models.CharField(choices=[('aceito', 'Aceito'), ('rejeitado', 'Rejeitado'), ('revisar', 'Revisar')], default='revisar', max_length=20),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Atribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_juri', models.CharField(choices=[('categoria', 'Júri de Categorias'), ('microtema', 'Júri de Microtemas')], default='categoria', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to=settings.AUTH_USER_MODEL)),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='trabalhos.trabalho')),
            ],
            options={
                'verbose_name': 'Atribuição',
                'verbose_name_plural': 'Atribuições',
                'unique_together': {('trabalho', 'avaliador', 'tipo_juri')},
            },
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='atribuicao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='trabalhos.atribuicao'),
        ),
    ]
